name: PeevesCI
on:
  push:
    branches:
      - master
      - edit

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_API_TOKEN }}
      - name: Test & Document
        uses: ./ci # Uses an action in the root directory

